source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

##################################################################################
##################################################################################
########################    GEM AGREGADAS   ######################################
##################################################################################
##################################################################################

# gemas básicas
#gem 'jquery-rails', '~> 4.3', '>= 4.3.3'
#gem 'jquery-ui-rails', '~> 6.0', '>= 6.0.1'
#gem 'bootstrap', '~> 4.1', '>= 4.1.3' # para usar bootstrap 4
gem 'will_paginate','3.1.6'
gem 'pry', '~> 0.11.3'

#gem 'font-awesome5-rails', '~> 1.0', '>= 1.0.1' # v5

gem 'data_migrate', '~> 4.0' # migraciones de datos separada

#gemas para la autorización
#gem 'cancancan', '~> 2.2'
#gem 'rolify', '~> 5.2'


#gemas para trabajar con datos
gem 'json', '~> 2.1'
#gem 'httparty', '~> 0.16.2'

#gemas para generar gráficos
#gem 'chart-js-rails', '~> 0.1.6'

#gemas para autentificación
#gem 'omniauth', '~> 1.8', '>= 1.8.1'
#gem 'omniauth-google-oauth2', '~> 0.4.1'
#gem 'devise', '~> 4.4', '>= 4.4.3'
#gem 'omniauth-azure-oauth2', '~> 0.0.9'

gem 'dotenv-rails', '~> 2.5', groups: [:development, :test]

group :development do
  gem 'capistrano', '~> 3.7', '>= 3.7.1'
  gem 'capistrano-rails', '~> 1.2'
  gem 'capistrano-passenger', '~> 0.2.0'

  # Add this if you're using rbenv
  gem 'capistrano-rbenv', '~> 2.1'
end

# gemas GIS
gem 'activerecord-postgis-adapter'

gem 'rgeo' 
gem 'rgeo-geojson'
gem 'rgeo-proj4'
gem 'pry-rails' # mejor consola
gem 'geocoder','1.4.4' # para sacar la información de la latitud y longitud